on:
  push:
  pull_request:

name: Check

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout repo content
      uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v2

    - name: install PyGame
      run: python3 -m pip install -U pygame --user

    - name: install ALSA
      run: sudo apt install libasound2

    - name: run script
      run: python main.py --test

